import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './products.html',
  styleUrls: ['./products.css'],
})
export class Products {
  products = [
    {
      id: 1,
      name: 'Infinix Hot 12',
      price: 7500,
      location: 'SM Baguio',
      details: '6.6-inch display, 4GB RAM, 64GB storage, 5000mAh battery',
    },
    {
      id: 2,
      name: 'Infinix Zero Ultra',
      price: 24999,
      location: 'SM Rosales',
      details: '6.8-inch AMOLED, 8GB RAM, 256GB, 200MP Camera, 4500mAh',
    },
    {
      id: 3,
      name: 'Infinix Note 12 G96',
      price: 11999,
      location: 'SM Tarlac',
      details: '6.7-inch AMOLED, 8GB RAM, 128GB, Helio G96',
    },
    {
      id: 4,
      name: 'Infinix Hot 30',
      price: 8999,
      location: 'SM Davao',
      details: '6.78-inch display, 8GB RAM, 128GB, 5000mAh',
    },
    {
      id: 5,
      name: 'Infinix Zero 20',
      price: 14999,
      location: 'SM San Fernando',
      details: '6.7-inch AMOLED, 8GB RAM, 256GB, 108MP camera',
    },
    {
      id: 6,
      name: 'Infinix Note 30',
      price: 10999,
      location: 'SM Cebu',
      details: '6.78-inch FHD+, Helio G99, 8GB RAM, 256GB, 5000mAh',
    },
    {
      id: 7,
      name: 'Infinix Smart 7',
      price: 4499,
      location: 'SM Manila',
      details: '6.6-inch display, 4GB RAM, 64GB storage, 5000mAh',
    },
    {
      id: 8,
      name: 'Infinix Hot 11 Play',
      price: 5999,
      location: 'SM Bacolod',
      details: '6.82-inch display, 4GB RAM, 128GB storage, 6000mAh',
    },
    {
      id: 9,
      name: 'Infinix Zero 5G 2023',
      price: 12999,
      location: 'SM Pampanga',
      details: 'Dimensity 920, 8GB RAM, 256GB, 6.78-inch FHD+',
    },
    {
      id: 10,
      name: 'Infinix Note 30 VIP',
      price: 15999,
      location: 'SM Iloilo',
      details: '120Hz AMOLED, 12GB RAM, 256GB, 108MP camera',
    },
    {
      id: 11,
      name: 'Infinix Hot 10',
      price: 6499,
      location: 'SM Clark',
      details: '6.78-inch display, 4GB RAM, 128GB storage, 5200mAh',
    },
    {
      id: 12,
      name: 'Infinix Note 11',
      price: 8999,
      location: 'SM Bataan',
      details: '6.7-inch AMOLED, Helio G88, 6GB RAM, 128GB',
    },
    {
      id: 13,
      name: 'Infinix Zero X Pro',
      price: 17999,
      location: 'SM Legazpi',
      details: '108MP periscope camera, 8GB RAM, 256GB, AMOLED',
    },
    {
      id: 14,
      name: 'Infinix Hot 9',
      price: 5999,
      location: 'SM Dagupan',
      details: '6.6-inch display, 4GB RAM, 64GB storage, 5000mAh',
    },
    {
      id: 15,
      name: 'Infinix Note 10 Pro',
      price: 11999,
      location: 'SM Subic',
      details: '6.95-inch FHD+, Helio G95, 8GB RAM, 256GB',
    },
    {
      id: 16,
      name: 'Infinix Smart 6',
      price: 4999,
      location: 'SM Batangas',
      details: '6.6-inch HD+, 3GB RAM, 64GB storage, 5000mAh',
    },
    {
      id: 17,
      name: 'Infinix Zero 8',
      price: 13999,
      location: 'SM Cabanatuan',
      details: '90Hz FHD+ display, Helio G90T, 8GB RAM, 128GB',
    },
    {
      id: 18,
      name: 'Infinix Hot 8',
      price: 5499,
      location: 'SM Laoag',
      details: '6.52-inch display, 4GB RAM, 64GB, 5000mAh',
    },
    {
      id: 19,
      name: 'Infinix Note 8',
      price: 10999,
      location: 'SM Palawan',
      details: '6.95-inch display, 6GB RAM, 128GB, Helio G80',
    },
    {
      id: 20,
      name: 'Infinix Smart 5',
      price: 4999,
      location: 'SM Tacloban',
      details: '6.6-inch display, 2GB RAM, 32GB storage, 5000mAh',
    },
    {
      id: 21,
      name: 'Infinix Zero 5',
      price: 9999,
      location: 'SM Calamba',
      details: '5.98-inch FHD, 6GB RAM, 64GB, dual camera',
    },
    {
      id: 22,
      name: 'Infinix Hot 20i',
      price: 6999,
      location: 'SM Taguig',
      details: '6.6-inch display, 4GB RAM, 128GB, 5000mAh',
    },
    {
      id: 23,
      name: 'Infinix Note 7',
      price: 8999,
      location: 'SM Antipolo',
      details: '6.95-inch FHD+, 6GB RAM, 128GB, Helio G70',
    },
    {
      id: 24,
      name: 'Infinix Hot 7 Pro',
      price: 5999,
      location: 'SM Naga',
      details: '6.2-inch HD+, 6GB RAM, 64GB storage, 4000mAh',
    },
    {
      id: 25,
      name: 'Infinix Smart HD 2021',
      price: 3999,
      location: 'SM Zamboanga',
      details: '6.1-inch HD+, 2GB RAM, 32GB, 5000mAh',
    },
  ];
}
